### ISSUE TITLE
zh_CN translation

### ISSUE THREAD

**Issue by OnceMore2020** [qmlbook/qmlbook#103]
There's a  simplified chinese version of qmlbook at : https://github.com/cwc1987/QmlBook-In-Chinese, but it's built with Gitbook. I want to know whether the translation branches (sub directories in this repo) are managed by qmlbook or driven by PR? So that the existing zh_CN version can be shifted here.

**Comment by OnceMore2020** [comment]
Found what I want here: https://github.com/qmlbook/qmlbook/blob/master/CONTRIBUTING.md#translations

**Comment by cwc1987** [comment]
Hi,I will do it, thanks for your suggestion.
