### ISSUE TITLE
Offer of general editing from a native speaker

### ISSUE THREAD

**Issue by LGundal** [qmlbook/qmlbook#12]
back-link: ch01/index.html#meet-qt-5

As a native speaker of American English and a relative newbie to Qt and QML, I would like to offer my services as time permits to help in editing your QML book. I am a software engineer with many years of experience (mostly in the Visual Studio world) who is very much enjoying the refreshing new world of QML but spending a lot of time banging my head against the wall because I can't find the relevant up-to-date documentation or conceptual ideas behind QML and Qt (5.4) so that I can code efficiently and "in the spirit of" the developers of this paradigm. Imagine my joy when I discovered your on-line book-in-progress! It hasn't quite fit my needs (yet), but it has given me some very helpful tips.

Therefore, as a return favor: I am extremely good at detecting typos, misspellings, bad grammar, etc. I would be more than willing, as time permits, to read over any chapter that is basically "finished" and clean up the English flaws, of which there were quite a few in this first chapter. I would rather not work on chapters "in progress", because I would have to re-read everything again each time you make changes. Your time is valuable. My time is valuable. Or perhaps you have plans to put off these kinds of corrections until just before publishing?

At any rate, I hope you will find some more time to continue with this book. It is sorely needed by all of the newbies out there who want to start learning Qt and QML. I jumped right in with V5.3 (now using 5.4) and discovered that much of the documentation is still geared to an older version and bears little resemblance to the New Project that was just generated for me by the Qt Creator (OK, I've got here a QQmlApplicationEngine. Why do all the examples use a QQuickView? What the heck is that? Do I need to dump my QQmlApplicationEngine? Because it doesn't have that rootObject() method I need from the example. etc. etc.). Or, even more basically, I was hopelessly stuck at the first window of the New Project wizard and didn't even know what kind of project I wanted to create! I hope your book will give us a leg up...

I will send additional issues as I discover them. However, I have decided to refrain from sending you issues for every little typo I find. That would bore the both of us.

Good luck! - Linda

**Comment by e8johan** [comment]
Hi Linda,

Thank you for your offer. It is much welcome!

The github interface lets you fork and then request a "pull request", i.e. for us to merge your changes back into the master branch. As you plan to work on the chapters closer to completion, I think that this would make sense (no risk of bad merges because someone decided to reshuffle the contents of an entire chapter).

Thanks for your offer to help and all your kind words!

Best regards,
Johan
