### ISSUE TITLE
Chapter on QML application deployment

### ISSUE THREAD

**Issue by probonopd** [qmlbook/qmlbook#148]
Sooner or later, a QML application is ready to be shipped to users. Developers may be interested how to package an application so that it can be used by Windows, macOS, and Linux users.

* For Windows, the [`windeployqt`](http://doc.qt.io/qt-5/windows-deployment.html) tool could be covered
* For macOS, the [`macdeployqt`](http://doc.qt.io/qt-5/osx-deployment.html) tool could be covered
* For Linux, [`linuxdeployqt`](https://github.com/probonopd/linuxdeployqt) tool could be covered

For an example on how to continuously build and package a simple "hello world" QML application using Travis CI and `linuxdeployqt` as an [AppImage](http://appimage.org/) that runs on many Linux distributions, see the https://github.com/probonopd/QtQuickApp example project.

**Comment by e8johan** [comment]
Adding it to the chapter queue.
