### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by m4sk1n** [qmlbook/qmlbook#149]
Hi, is this project alive? Will there be some new chapters?

**Comment by fer-rum** [comment]
A bunch of forks seem to exist, which added stuff, but did so far not feed back anything into master.

**Comment by m4sk1n** [comment]
@fer-rum Is there fork that tries to be maintained fork of this great book with all additions?

**Comment by fer-rum** [comment]
Probably no. (?) Maybe you can make one and merge all these changes from the other forks?

**Comment by m4sk1n** [comment]
@fer-rum, it seems that there aren't any pull requests with new content, only translations and fixes

**Comment by fer-rum** [comment]
Better then nothing, I suppose. But yeah, this project might need a fresh community boost.

**Comment by jryannel** [comment]
Hi, 

Please read to the end...

The author (me) got a baby 10 month ago and needed to pause the efforts here. The little one will be soon one year and my plans are not to add any chapters to this book as I see it complete for an introduction book.

We will update the content for new Qt versions. The next one should be 5.9 update.

Nevertheless I plan to write a second book with more application centric content. I'm currently collecting material. As soon as I will have spare time again (which is hopefully during June) I will setup a second repository for the new book and collect input from contributors also I'm curios how to best setup such an community effort.

See you all in June

**Comment by m4sk1n** [comment]
Thanks, @jryannel. I understand. Maybe I'll review Polish translation of this book and complete it. :)

**Comment by fer-rum** [comment]
And with these words, I think you can close the issue as "Don't Panic".

**Comment by j9ac9k** [comment]
@jryannel parent of 16 month old here, congratulations on the addition to your family!  I also rapidly slowed down any work on extracurricular activities.  Please don't be afraid to post up an issue asking for help from the community whenever you need it.

**Comment by Intellugo** [comment]
Well and Sound
