### ISSUE TITLE
No assets folder.

### ISSUE THREAD

**Issue by pixelgrease** [qmlbook/qmlbook#16]
back-link: ch01/index.html#meet-qt-5

The very first note reads: "The source code of this chapter can be found in the **assets folder**."

But clicking the **assets folder** link gets a 404 error. 

So where can *I* find the assets?

**Comment by jryannel** [comment]
This should be fixed now. Try it out

**Comment by pixelgrease** [comment]
Yes, works now. Thank you for the fast turnaround!
