### ISSUE TITLE
Repetition of code

### ISSUE THREAD

**Issue by gareth-j** [qmlbook/qmlbook#181]
back-link: en/ch16/index.html#extending-qml-with-c

16.5.5

```
FileIO {
    id: io
}

```

This piece of code, which is first shown in  16.5.4. Reading Data  is repeated unnecessarily in 16.5.5. Writing Data

**Comment by e8johan** [comment]
You are correct from one perspective, but as FileIO is central to both snippets and they appear under different headings, I would prefer to keep it. Also, adding it twice in your code gives a pretty clear error message, so the risk of unexpected behaviour is fairly low.
