### ISSUE TITLE
License of the contributions

### ISSUE THREAD

**Issue by hckr** [qmlbook/qmlbook#201]
I've just found your book and repo, and looked inside CONTRUBUTING.md, where you say:

> You provide us the contributions under the Attribution-NonCommercial-ShareAlike 4.0 International license for text and the BSD license for code. We keep the rights to print a book based on the provided content.

So, the license of the text and contributed changes is for non-commercial use (as it is stated in README.md and LICENSE.text), but the owners of the repo have additional right to use it commercially? If you mention it only in CONTRIBUTING.md and not in other places, does it even have a legal power? (I'm just curious.)

**Comment by e8johan** [comment]
I am not a lawyer and we myself and Juergen also try to keep this extremely simple. 

To ensure that everyone sees this we use a CLA checking agent that ensures that everyone is up to date before pushing a change, so I hope it works legally. 

In addition, we try to be clear that the door we want to keep open is to put the words onto pieces dead trees at some point. That is the whole purpose of the CLA. From that perspective, I hope that you feel this is a fair and transparent deal.
