### ISSUE TITLE
Chapter 6 File Dialog doesn't work correctly on Android

### ISSUE THREAD

**Issue by edips** [qmlbook/qmlbook#225]
I tried the example "image viewer" on Android, and desktop. It works well on desktop but it works very bad on Android like picture:
![screenshot_2019-01-06-23-08-07-562_org qtproject example imageviewer_mobile](https://user-images.githubusercontent.com/3856713/50741028-fc184c80-1208-11e9-8c92-e3b1999d215f.png)

**Comment by e8johan** [comment]
That was not very nice. Let me have a closer look at it.

**Comment by e8johan** [comment]
This is a Qt bug. I reported it here: https://bugreports.qt.io/browse/QTBUG-73115 .

**Comment by edips** [comment]
Thanks. Now I understand how native file dialog works with `import Qt.labs.platform 1.0 as Platform` from the Controls documentation.
