### ISSUE TITLE
all example codes are empty.

### ISSUE THREAD

**Issue by bizos** [qmlbook/qmlbook#226]
I've download all source code examples from http://qmlbook.github.io/assets/#  , but the downloaded files are all 45-bytes tgz files. There contents are all the same: empty. 
Can anybody tell me where can I download the real Source Code Examples?

**Comment by e8johan** [comment]
That is bad. Thank you for reporting.

While I fix this, you can find all code here: https://github.com/qmlbook/qmlbook/tree/master/docs . Look under src in each chapter directory.

**Comment by e8johan** [comment]
It seems like the --exclude path of the tar commands was a bit to broad. I'm still not 100% sure as to why, but now the tarballs have contents.
