### ISSUE TITLE
How to access prorected method from QML

### ISSUE THREAD

**Issue by phantomgz** [qmlbook/qmlbook#246]
Hi, when I reading this book, in chapter 16.5.2, declare a protected method 

        protected:
            virtual QHash<int, QByteArray> roleNames() const override; 

It's overide from **QAbstractListModel**, in there are declare as a public method, why do this change? and how QML call a protected method in C++ class.

**Comment by e8johan** [comment]
QAbstractListModel can call into protected methods. then QML talks to QAbstractListModel through a private API, which is may, as they are a part of the same Qt release.
