### ISSUE TITLE
 void setName(const QString &); must be  void setName( QString &);

### ISSUE THREAD

**Issue by fro0m** [qmlbook/qmlbook#33]
back-link: ch15/index.html#the-qobject

Am I right? please write to me if first is right because is really confuses me as a newbie.

**Comment by e8johan** [comment]
const QString & is correct, as this refers to the string given to the function. I.e. the input reference is not changed. Compare this to QString name() const, which indicates that the name is returned without modifying the object state, i.e. the name stored in the object.

**Comment by bergmansj** [comment]
eJohan beat me to the answer :) 
It is customary (and sensible) to pass parameters as const references.
Furthermore, in the case of a const QString& (just like the case with const std::string&) you get the ability to pass a string literal, which is a const char* in C/C++.

**Comment by fro0m** [comment]
Well, Thank you for the answer
void setName(const QString &); means that reference can not be change BUT the reffered object may be changed.
Now it is clear.
