### ISSUE TITLE
Page not found - http://qmlbook.github.io/en/assets

### ISSUE THREAD

**Issue by pas7** [qmlbook/qmlbook#39]
back-link: en/ch05/index.html#fluid-elements

Good afternoon,
Thank you for a great book.
On some pages, there is a link http://qmlbook.github.io/en/assets
But when you go to it - Error 404 Page Not Found

**Comment by pas7** [comment]
but it is a folder
http://qmlbook.github.io/assets/
probably did not change the links in the book

**Comment by jryannel** [comment]
Correct. The paths are calculated relative. As we move the page under the "en" folder for translation. Thx for reporting.

**Comment by jryannel** [comment]
This should be fixed now. Please verify.
