### ISSUE TITLE
QtGui: No such file or directory

### ISSUE THREAD

**Issue by stegrams** [qmlbook/qmlbook#41]
back-link: en/ch02/index.html#widget-application

I m using ubuntu-sdk's Qt Creator.
On main.cpp of the Console Application project I created for previous examples, I paste the Widget Application code and got this error
```
../console-example/main.cpp:1:17: fatal error: QtGui: No such file or directory
 #include <QtGui>
                 ^
```
Should I have to create some other kind project to run this snippet?

Thanks in advanced

**Comment by jryannel** [comment]
QtConsole apps link only against QtCore. You need to add QT += QtGui to the make file.
