### ISSUE TITLE
PDF bookmarks

### ISSUE THREAD

**Issue by gdwhite** [qmlbook/qmlbook#43]
The numbering of the PDF bookmarks don't match the online version and there are no bookmarks deeper than chapter level (i.e.sections):

![qmlbook pdf bookmarks](https://cloud.githubusercontent.com/assets/2054830/7576905/b56fe6be-f810-11e4-8f6a-a3a41f4991ae.png)

Is it possible to modify the build process in order to rectify this?

Thanks,
Gary

**Comment by jryannel** [comment]
This should be solved now. Please check it out.

**Comment by gdwhite** [comment]
Thank you very much Juergen.
Also, thanks for creating the book.  It should prove very helpful.
Gary
