### ISSUE TITLE
Move to python3 or specify python version

### ISSUE THREAD

**Issue by 29jm** [qmlbook/qmlbook#61]
On Archlinux python3 is the default python interpreter and `make html` gives errors because of that. I see two possible solutions: switching to python3 (better in my opinion: more recent, etc..), or modifying the build system to specify `python2` and not just `python`.
I just ran every python file through `2to3` and it worked perfectly after that, so that might be an easy option.
I really like this book by the way!

**Comment by e8johan** [comment]
We've decided to go with python 3 and will update the text accordingly. This is tracked in #176 .
