### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by ghost** [qmlbook/qmlbook#8]
I think that it'd be a great idea to add documentation to Python specifically the PyQt5 binding, it is a great option to developers.

**Comment by jryannel** [comment]
True. Might think about in a later chapter. Would you think about QtWidgets and Python or QML and Python?

**Comment by isaaccortes** [comment]
Sorry for the delay; but I was in a tough semester. But I was thinking more in the QtWidgets+Python aspect rather than QML. I'm not very fan of QML and the majority of the code in PyQt5 I've watched was with the QtWidgets module.

**Comment by e8johan** [comment]
Adding it to the chapter queue.
