### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sajis997** [qmlbook/qmlbook#9]
Having the following output while trying to compile in ubuntu 14.04 with Qt 5.2  installation.

///////////////////////////////////////////////////

sajjad@sajjad-G74Sx:~/Documents/Books/Qt/qml/qmlbook-master$ make 
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: Command not found
make: *** [html] Error 127

//////////////////////////////////////////////////

Any idea ?

**Comment by e8johan** [comment]
It seems that you have not installed the sphinx-doc toolchain. You can always access the contents on qmlbook.org, there is no need to build it locally.
